apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: clima-rabbit
  namespace: proyecto2
spec:
  replicas: 1 
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "700m"
      memory: "2Gi"
  persistence:
    storage: "10Gi"