apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: clima-rabbit
  namespace: proyecto2
spec:
  replicas: 1 
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"