apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: clima-topic
  namespace: proyecto2
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 1641600000  # 7 días
    segment.bytes: 1073741824 # 1GB