apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-writer
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-writer
  template:
    metadata:
      labels:
        app: kafka-writer
    spec:
      containers:
      - name: kafka-writer
        image: 34.70.50.55.nip.io/proyecto2/kafka-writer:latest
        ports:
        - containerPort: 50052
        
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-writer
  namespace: proyecto2
spec:
  selector:
    app: kafka-writer
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
  type: ClusterIP  # Solo accesible dentro del clúster