# 
FROM python:3.9-slim

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

VOLUME /app/logs
RUN mkdir -p /app/logs && \
    touch /app/logs/logs.json

# 
COPY ./ /code/

# 
CMD ["fastapi", "run", "main.py", "--port", "5000"]